schemes:
  dracula: &dracula
    primary:
      background: '#14151b'
      foreground: '#7a7a7a'
    normal:
      black:      '#14151b'
      red:        '#e23a40'
      green:      '#009219'
      yellow:     '#748115'
      blue:       '#8e67c8'
      magenta:    '#cb4897'
      cyan:       '#118699'
      white:      '#4e4e52'
    bright:
      black:      '#221d21'
      red:        '#d64a48'
      green:      '#009132'
      yellow:     '#78802b'
      blue:       '#8a6cb8'
      magenta:    '#bd5693'
      cyan:       '#2a8695'
      white:      '#7a7a7a'
colors: *dracula
