schemes:
  gentledark: &gentledark
    primary:
      background: '#121217'  # HSV: 240, 20,  9
      foreground: '#828282'  # HSV:   0,  0, 51
    normal:
      black:      '#121217'  # HSV: 240, 20,  9
      red:        '#b66e72'  # HSV: 357, 39, 71
      green:      '#5e8d5c'  # HSV: 117, 35, 55
      yellow:     '#a6785d'  # HSV:  22, 44, 65
      blue:       '#7f7eae'  # HSV: 241, 28, 68
      magenta:    '#af6d98'  # HSV: 321, 38, 69
      cyan:       '#518b91'  # HSV: 185, 44, 57
      white:      '#4f4f59'  # HSV: 240, 11, 35
    bright:
      black:      '#201c21'  # HSV: 290, 15, 13
      red:        '#b37169'  # HSV:   6, 41, 70
      green:      '#5c8d6e'  # HSV: 142, 35, 55
      yellow:     '#997e52'  # HSV:  37, 47, 60
      blue:       '#9776a6'  # HSV: 280, 29, 65
      magenta:    '#b16f84'  # HSV: 341, 37, 69
      cyan:       '#5a8999'  # HSV: 195, 41, 60
      white:      '#828282'  # HSV:   0,  0, 51
colors: *gentledark
