schemes:
  gentledark: &gentledark
    primary:
      background: '#18181f'
      foreground: '#828282'
    normal:
      black:      '#18181f'
      red:        '#b66e71'
      green:      '#5e8d5c'
      yellow:     '#a6785d'
      blue:       '#7f7eae'
      magenta:    '#af6d98'
      cyan:       '#518b90'
      white:      '#474759'
    bright:
      black:      '#241b26'
      red:        '#b3716a'
      green:      '#5c8d6f'
      yellow:     '#997e51'
      blue:       '#9776a6'
      magenta:    '#b16f84'
      cyan:       '#5a8999'
      white:      '#828282'
colors: *gentledark
