schemes:
  grayscale: &grayscale
    primary:
      background: '#0f0f0f'
      foreground: '#8c8c8c'
    normal:
      black:      '#0f0f0f'
      red:        '#737373'
      green:      '#8c8c8c'
      yellow:     '#808080'
      blue:       '#666666'
      magenta:    '#949494'
      cyan:       '#999999'
      white:      '#454545'
    bright:
      black:      '#1c1c1c'
      red:        '#787878'
      green:      '#919191'
      yellow:     '#858585'
      blue:       '#737373'
      magenta:    '#969696'
      cyan:       '#9e9e9e'
      white:      '#8c8c8c'
colors: *grayscale
