schemes:
  green: &green
    primary:
      background: '#121217'
      foreground: '#30b200'
    normal:
      black:      '#121217'
      red:        '#9aa055'
      green:      '#55ae3f'
      yellow:     '#8da445'
      blue:       '#70a77c'
      magenta:    '#96a071'
      cyan:       '#4dae65'
      white:      '#4f4f59'
    bright:
      black:      '#201c21'
      red:        '#97a14f'
      green:      '#54ae4d'
      yellow:     '#82a73b'
      blue:       '#82a478'
      magenta:    '#97a062'
      cyan:       '#54ad6b'
      white:      '#30b200'
colors: *green
