# vim:ft=sh
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

HISTFILE=~/.bash_history

bind 'set enable-keypad on'
bind 'set show-all-if-ambiguous off'
#bind 'set completion-map-case on'
bind 'set completion-ignore-case on'
#bind 'set completion-prefix-display-length 5'
bind 'set colored-completion-prefix on'
bind 'set colored-stats on'

bind '\C-w:backward-kill-word'
bind 'set bind-tty-special-chars Off'

PS1_start=""
PS1_np_beg="\\001"
PS1_np_end="\\002"

[ -r ~/.shellsrc ] && . ~/.shellsrc
